# Header
menu:
  Home: /
  Archives: /archives
  Research: /research
  Links: /links
  About: /about


# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tags: false
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: http://github.com/quxiaofeng
  twitter: http://twitter.com/quxiaofeng
  facebook: http://facebook.com/quxiaofeng
  # dribbble: http://dribbble.com/quxiaofeng
  zhihu: http://www.zhihu.com/people/quxiaofeng
  douban: http://www.douban.com/people/gBlueBird
  weibo: http://www.weibo.com/quxiaofeng
  rss: /atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics: UA-50831338-1
favicon: /css/images/favicon.png
twitter: http://twitter.com/quxiaofeng
google_plus:
fb_admins:
fb_app_id:
